### ISSUE TITLE
[DOCS] Write comments

### ISSUE THREAD

**Issue by KendallDoesCoding** [KendallDoesCoding/penny-lane#2]
Try to understand what the code does and write a comment on how it works in HTML, CSS, JS files.

**Comment by Arman-ali-khan-786** [comment]
can i work on this issue??

**Comment by KendallDoesCoding** [comment]
> can i work on this issue??

Sure!

**Comment by RohitRajvaidya5** [comment]
Is this issue resolved I want to contribute

**Comment by KendallDoesCoding** [comment]
No. But last I heard, @Arman-ali-khan-786 was working on this but no update from him from the last month.

Please let me know if ur still working on this or if I can assign this to Rohit at the earliest @Arman-ali-khan-786

**Comment by Arman-ali-khan-786** [comment]
> No. But last I heard, @Arman-ali-khan-786 was working on this but no update from him from the last month.
> 
> Please let me know if ur still working on this or if I can assign this to Rohit at the earliest @Arman-ali-khan-786

yeah i was working on in and i have opened a pr for the same plz check it if changes required do let me know @KendallDoesCoding

**Comment by Arman-ali-khan-786** [comment]
before closing the issue do assign it to be you haven't yet assigned me officially ;)

**Comment by KendallDoesCoding** [comment]
> before closing the issue do assign it to be you haven't yet assigned me officially ;)

yeah, my bad.
